### ISSUE TITLE
Clic pour dessiner

### ISSUE THREAD

**Issue by JC-Cpz** [foucdeg/passe-un-dessin#29]
Yo, les clics gauches simples pour changer de couleurs ou faire des points marchent pas tout le temps
Sinon le jeu est très cool !
JC

**Comment by foucdeg** [comment]
@JC-Cpz faire des points ça devrait être ok depuis 1 heure :)

**Comment by foucdeg** [comment]
Pourquoi t'as parlé de lobby dans le titre sinon ?

**Comment by JC-Cpz** [comment]
Ah mince j'ai oublié de retirer ca ^^"
J'avais penser à rajouter un vrai lobby qui prend tout l'écran et pas juste la petite fenetre mais apres réflexion je me suis dit que c'était pas nécessaire  ;)

**Comment by foucdeg** [comment]
Normalement corrigé par @RobotScribe , si t'as l'occasion de retester @JC-Cpz
