### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by foucdeg** [foucdeg/passe-un-dessin#475]
# Idée générale

L'avatar sert à rendre plus visuel les joueurs.
L'avatar sert aussi de tuto de dessin : dans le cadre du tuto, on est amené à dessiner son avatar.
Les gens qui n'ont pas choisi leur avatar ont un avatar par défaut un peu moche (fais toi plaiz @RobotScribe )

## Endroits où l'avatar se voit

- PlayerModal : son propre avatar
- Lobby : on voit tout le monde
- Classement partie
- Leaderboard (à la place du PlayerChip)
- Page de détails joueur

Garder les PlayerChip classiques sur la progression en haut de la game, les gens qui ont pas fini ...

## Comment on set son avatar

- via le mode modifier de la PlayerModal (éventuellement faire une grande zone pour ça) - bonus : permettre de modifier la couleur aussi
- via le tuto

## Tech

- stocker la data sur le Player de la même manière que les PadStep
- comme pour les PadStep, ne jamais retourner la data dans du json, mais retourner une URL vers l'avatar qui passe par le microservice de rendu png
- ne pas hésiter à faire une zone de dessin 3 à 4x plus grosse que le vrai rendu de l'avatar (et l'enregistrer en grand même si on l'affiche en petit). 
- problème à résoudre : est-il possible de modifier son avatar sans le recommencer de zéro ?
  - solution possible : dumper le PNG actuel dans le canvas ?
- problème à résoudre : l'avatar est en cache front et back donc s'il change c'est chaud que tout le monde voie la modif
  - solution possible : l'avatar est un modèle à part en OneToOne avec le joueur, comme ça dessin différent = url différente

**Comment by RobotScribe** [comment]
done
