### ISSUE TITLE
ETQU, quand je rentre une description de dessin trop longues je vois une erreur

### ISSUE THREAD

**Issue by AlixBou** [foucdeg/passe-un-dessin#487]
Quand on devine le mot de quelqu'un, si le mot à deviner est trop long, on ne peut pas valider mais il n'y a pas de messages d'erreur

**Comment by foucdeg** [comment]
yes 100 caractères en effet, ça manque d'une validation front

**Comment by Matt-Blt** [comment]
Un compteur de caractères sous la zone de texte aiderait à ne pas dépasser la limite, et éviterait l'affichage d'un message d'erreur intrusif

**Comment by foucdeg** [comment]
Je pense que je vais déjà faire en sorte que "ça ne tape plus" après 100 caractères
