### ISSUE TITLE
ETQU, je vois distinctement le nombre de vote qui me reste

### ISSUE THREAD

**Issue by AlixBou** [foucdeg/passe-un-dessin#488]
Les pouces violets sur le fond violet ne se voient presque pas

**Comment by foucdeg** [comment]
oui ça me gêne depuis un moment ça. Faut que je voie s'il y a une couleur objectivement mieux que le violet à cet endroit, plutôt que de mettre un background ou un outline

**Comment by AlixBou** [comment]
Je pense que le jaune ou le vert des extrémités de l'écran iraient bien. Comme ça on reste dans les couleurs de l'écran mais on est sûr de ne pas être ton sur ton quelque soit la taille de l'écran

**Comment by foucdeg** [comment]
Resolved by #547
