### ISSUE TITLE
ETQU, l'interface de dessin est plus complète

### ISSUE THREAD

**Issue by AlixBou** [foucdeg/passe-un-dessin#490]
Rajouter des couleurs pour permettre de dessiner des dessins plus complexes
Améliorer le bouton annuler (il supprime parfois des traits précédents) et pouvoir faire ctrl+Z

**Comment by foucdeg** [comment]
Le bug du bouton annuler, jamais vu pour le coup. Peut-être un lag qui a poussé l'utilisateur à cliquer deux fois ?

Control-Z ça se fait bien, c'est une bonne idée (cmd-Z sur mac aussi)

Rajouter des couleurs je suis pas trop convaincu. On pourrait aussi mettre un color picker complet, mais les gens perdraient du temps à choisir. Tu trouves qu'il manque certaines couleurs en particulier ?

**Comment by AlixBou** [comment]
Pour moi en couleur, il faudrait en plus un vert clair,  et modifier le magenta pour avoir un vrai violet et un vrai rose.

**Comment by Matt-Blt** [comment]
Pull Request soumise pour ajouter les nouvelles couleurs suggérées.
