### ISSUE TITLE
Mode anonyme ?

### ISSUE THREAD

**Issue by foucdeg** [foucdeg/passe-un-dessin#498]
> Les gens dans les parties commencent à dire « on vote pas Melbius » 😡
> _- Melbius_

bref, en soi c'est pas dur, une option de game purement front qui permettrait de ne pas afficher de noms : 

- juste au récap : mais c'est inférable par la connaissance des joueurs avant/après (en plus c'est les mêmes de toute la game) donc un joueur donné sait reconnaître ses dessins plus ceux des gens d'avant et d'après
- en game et au récap : risque de moins d'ambiance si tu sais pas à qui reprocher le dessin de merde que t'as reçu

Il faut aussi éviter d'afficher la progression de la game telle quelle, et afficher les Pad en ordre aléatoire au récap.

**Comment by foucdeg** [comment]
ouais et en plus même au récap c'est soit parfaitement silencieux soit un peu grillé (on est obligé de se révéler pour râler sur un dessin) - et au moment du résultat des votes, on n'a plus accès au récap. Donc je sais pas trop.

**Comment by RobotScribe** [comment]
Pas sur que ça soit une feature de ouf. C'est pas un jeu où on va être hyper compétitif non plus, les gens sont la pour s'amuser on va pas se dire "si je veux le rattraper faut pas que je vote pour lui"

**Comment by foucdeg** [comment]
bah @maxenceg dit qu'il a eu le cas, mais on peut pas en être sûr, ce mec se la pète un peu des fois

**Comment by foucdeg** [comment]
Mais ouais on close pour le moment.
