### ISSUE TITLE
Retours des potes de Matthieu

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#522]
Plusieurs retours suite à des parties faites avec mes amis.

**Suggestions**

- _Créer un système de matchmaking_
Nous avons fait quelques parties où nous n'étions que trois ou quatre, et avoir un peu plus de monde aurait été chouette. L'idée serait de permettre d'ouvrir le salon à n'importe qui (avec une limite de joueurs), et des joueurs qui ne disposent pas du lien pourraient tout de même rejoindre le salon à travers une liste de salons disponibles.

- _Palettes de couleurs personnalisées_
La question de personnaliser les couleurs que l'on choisit a déjà été évoquée, mais était contraignante car elle interromprait le processus de dessin en cours de partie. Ici, le joueur pourrait personnaliser dans son profil les couleurs dont il souhaite disposer avant une partie. On pourrait même imaginer un système de palettes de couleurs. Plusieurs cas sont envisageables : 
-> Le joueur dispose d'une seule palette de n slots, et il peut assigner n'importe quelle couleur à ce slot
-> Le joueur dispose de plusieurs palettes qu'il peut personnaliser à volonté, et choisit celle qu'il utilise au début du jeu
-> Comme ci-dessus, mais les différentes palettes sont prédéfinies (classique, saturée, pastel, automne, givre, crépuscule, ...)

- _Modes de jeu_
Pour corser un peu les choses, le maître du jeu pourrait imposer des conditions aux joueurs lors de la partie. Quelques idées : 
-> Le dessin ne peut être fait qu'en un seul trait, impossible de lever le crayon
-> Une palette de couleurs est imposée à tous les joueurs
-> Noir et blanc uniquement
-> Le joueur ne voit que les n derniers traits qu'il a dessinés, les autres deviennent invisibles jusqu'à la fin du dessin

**Bugs**

- _La page où le joueur doit choisir un mot freeze parfois_
Il doit alors rafraîchir ou attendre que ça unfreeze. Personnellement, je n'ai jamais eu de problème, donc cela doit dépendre du PC ou du navigateur.

- _Un joueur qui se connecte dans un salon peut se voit en double_
Son nom est dupliqué dans la liste des participants. Les autres joueurs ne le voient cependant pas en double. Ce n'est pas systématique.

- _Se connecter à son compte alors que l'on est déjà dans un salon ne déconnecte pas l'invité_
Je me connecte en tant que "toto" à un salon. Je décide de me connecter avec mon compte Matsou. Une fois connecté, toto et Matsou sont tous les deux dans la partie, toto n'a pas été déconnecté.

- _Modifier son mot n'enlève pas le statut Prêt_
J'écris un mot (en début ou en cours de partie) que je valide, je ne figure donc plus dans la liste des joueurs que l'on attend. Lorsque je modifie mon mot, je demeure toujours parmi les joueurs qui sont prêts. Si les derniers joueurs valident, l'étape suivante commence alors que j'étais en train d'éditer mon mot.

- _window.FB is undefined_
Bug qu'a eu une amie sur Firefox 82.0.2 64bits. Quand elle clique sur le bouton "Joueur", pour se connecter à son compte par exemple, elle tombe sur la page "Sorry, this is not working properly". Erreur console : 
`TypeError: window.FB is undefined (LogInWithFacebook.tsx:57)`
Je n'ai personnellement pas réussi à reproduire le bug.

**Comment by foucdeg** [comment]
Merci pour ça !
Ca t'embête pas de faire une issue par sujet pour qu'on puisse faire une PR par sujet ? :)

**Comment by foucdeg** [comment]
Merci d'avoir créé les issues, j'archive celle-ci :)
