### ISSUE TITLE
Discord pour trouver des parties

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#532]
Nous avons fait quelques parties où nous n'étions que trois ou quatre, et avoir un peu plus de monde aurait été chouette. L'idée serait de permettre d'ouvrir le salon à n'importe qui (avec une limite de joueurs), et des joueurs qui ne disposent pas du lien pourraient tout de même rejoindre le salon à travers une liste de salons disponibles.

**Comment by foucdeg** [comment]
Sans lien visio / audio, ça enlève du charme, non ?

Pour l'instant ça reste important de communiquer quand on part, parce que le type lambda bah s'il se casse sans prévenir il nique une partie. Donc je doute un peu.

Sauf si on inclut le canal audio au jeu ...

**Comment by foucdeg** [comment]
Alternativement, un forum / chatroom où tu trouves des gens chauds et tu les invites à ton appel de groupe + ton salon.

**Comment by Matt-Blt** [comment]
J'avoue que ça enlève du charme de ne pas être en vocal, et si un lambda qui la partie en plein milieu, ça casse tout.
L'alternative la plus simple serait sûrement un serveur Discord avec des salons vocaux disponibles et que tout le monde peut rejoindre.

**Comment by foucdeg** [comment]
ouais j'avoue je lance juste un discord

**Comment by foucdeg** [comment]
donc : 

- j'ai créé le discord : https://discord.gg/xvUzS9GJ
- il faut modifier la home pour proposer un lien vers le discord (et déplacer les règles dans une modale)

**Comment by foucdeg** [comment]
Resolved in #563
