### ISSUE TITLE
Palettes de couleurs personnalisées

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#533]
La question de personnaliser les couleurs que l'on choisit a déjà été évoquée, mais était contraignante car elle interromprait le processus de dessin en cours de partie. Ici, le joueur pourrait personnaliser dans son profil les couleurs dont il souhaite disposer avant une partie. On pourrait même imaginer un système de palettes de couleurs. Plusieurs cas sont envisageables :
-> Le joueur dispose d'une seule palette de n slots, et il peut assigner n'importe quelle couleur à ce slot
-> Le joueur dispose de plusieurs palettes qu'il peut personnaliser à volonté, et choisit celle qu'il utilise au début du jeu
-> Comme ci-dessus, mais les différentes palettes sont prédéfinies (classique, saturée, pastel, automne, givre, crépuscule, ...)

**Comment by foucdeg** [comment]
Cette idée-là, honnêtement, je ne l'aime vraiment pas, pour des raisons qui sont un peu floues dans ma tête mais que je vais essayer d'expliquer ci-dessous.

L'esprit du jeu (tel que je le vois) est de faire des dessins clairs et efficaces, ce n'est pas une appli de dessin d'art. Avoir les bonnes couleurs exactement ne me semble vraiment pas être d'un intérêt quelconque pour "être fort" au jeu. Volontairement, Passe un Dessin a un style criard et flash voire enfantin parce qu'on attend des dessins du même genre et que c'est ça qui font que ceux qui savent mal dessiner se sentent inclus. Cet ajout servirait au contraire à une élite de gens talentueux qui sortiraient des oeuvres superbes qui feraient peux aux nouveaux. Ce serait dommage.

Je respecte les gens qui font des oeuvres d'art avec Paint, ou de l'architecture sur Minecraft, mais là, comme le dit la tagline du jeu, c'est pour les gens qui ne savent pas dessiner.

**Comment by foucdeg** [comment]
Bon, tu n'as pas contesté donc j'archive :)
