### ISSUE TITLE
La page où le joueur doit choisir un mot freeze parfois

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#535]
Il doit alors rafraîchir ou attendre que ça unfreeze. Personnellement, je n'ai jamais eu de problème, donc cela doit dépendre du PC ou du navigateur.

**Comment by foucdeg** [comment]
aucune idée non plus, mais c'est probable qu'on teste pas assez sur Firefox ...

**Comment by Matt-Blt** [comment]
J'ai eu un retour de la personne qui m'a reporté ce bug, elle n'a plus le problème ! Je ferme l'issue.
