### ISSUE TITLE
Se connecter à son compte alors que l'on est déjà dans un salon ne déconnecte pas l'invité

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#537]
Je me connecte en tant que "toto" à un salon. Je décide de me connecter avec mon compte Matsou. Une fois connecté, toto et Matsou sont tous les deux dans la partie, toto n'a pas été déconnecté.

**Comment by foucdeg** [comment]
Vrai gros bug ça, merci !

**Comment by foucdeg** [comment]
bon en fait c'est juste de l'affichage, non ? Si tu recharges la room toto disparaît chez moi.

Du coup ça se rapproche de #521 j'ai l'impression
