### ISSUE TITLE
Modifier son mot n'enlève pas le statut Prêt

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#538]
J'écris un mot (en début ou en cours de partie) que je valide, je ne figure donc plus dans la liste des joueurs que l'on attend. Lorsque je modifie mon mot, je demeure toujours parmi les joueurs qui sont prêts. Si les derniers joueurs valident, l'étape suivante commence alors que j'étais en train d'éditer mon mot.

**Comment by foucdeg** [comment]
bon après ça je t'avoue que c'était un peu voulu pour éviter que les gens tergiversent trop longtemps. Mais on peut revenir dessus.

**Comment by foucdeg** [comment]
à grouper avec https://github.com/foucdeg/passe-un-dessin/issues/182

**Comment by Matt-Blt** [comment]
Lors de mes parties, on est souvent en vocal, et si quelqu'un met trop de temps pour trouver un mot, il y a toujours un moment où les autres joueurs mettent un petit coup de pression pour que les derniers se dépêchent :smile: 
Personnellement, je pense que le passage à l'étape suivante alors qu'on modifie son mot est plus frustrant (et inattendu) que l'attente. Aussi, lorsque l'on modifie son mot, c'est qu'on a déjà une idée en tête, donc la modification et validation sont rapides.

**Comment by foucdeg** [comment]
bon j'ai regardé un peu le truc.

On rencontre le problème que mentionnait @RobotScribe sur la dénormalisation de la BDD avec le champ pads_done sur la game : en se permettant de décrémenter / réincrémenter ce champ, on risque fort de désynchroniser sa valeur de la réalité. Par exemple si on rate le message où un joueur signalait être en train de modifier son mot (ce qui doit décrémenter) mais qu'on capte son 2e submit (ce qui doit incrémenter) => on incrémente une fois de trop et on passe à la suite sans quelqu'un.

Aujourd'hui, pads_done est incrémenté uniquement au premier submit de chaque step, et décrémenté seulement lors des votes et en association avec une réelle suppression d'un vote. Là, on le décrémenterait sans setter à null le mot*, donc : 
- déjà on se met dans la merde vis-à-vis de #182 vu que le back ne peut pas "se souvenir" ni retrouver qui est en train d'éditer son mot si on lui demande
- et puis cf risque ci-dessus. 

2 versions dont ça peut quand même marcher : 

- on set le mot à null lorsque la personne modifie, à condition de vérifier que le player en question est bien à la phase en question sur le pad / padstep en question etc ; on décrémente le compteur ; au submit, on réincrémente si le mot était null. #182 devient du pur front, trouver la step de qui est null
- pads_done devient un tableau des ID des joueurs qui n'ont pas terminé, comme ça un joueur s'enlève et se remet de la liste et est capable de ne pas incrémenter et décrémenter s'il n'est déjà pas là / déjà là.
