### ISSUE TITLE
window.FB is undefined

### ISSUE THREAD

**Issue by Matt-Blt** [foucdeg/passe-un-dessin#539]
Bug qu'a eu une amie sur Firefox 82.0.2 64bits. Quand elle clique sur le bouton "Joueur", pour se connecter à son compte par exemple, elle tombe sur la page "Sorry, this is not working properly". Erreur console :
`TypeError: window.FB is undefined (LogInWithFacebook.tsx:57)`
Je n'ai personnellement pas réussi à reproduire le bug.

**Comment by Matt-Blt** [comment]
![image](https://user-images.githubusercontent.com/73788012/98595692-9c909980-22d6-11eb-8eb4-caa0a4c9a93d.png)

**Comment by foucdeg** [comment]
A priori même problème que https://github.com/foucdeg/passe-un-dessin/issues/482

**Comment by foucdeg** [comment]
Du coup j'archive car duplicate

**Comment by foucdeg** [comment]
et c'est corrigé :)
