### ISSUE TITLE
Rechercher des joueurs les joueurs dans le leaderboard

### ISSUE THREAD

**Issue by RobotScribe** [foucdeg/passe-un-dessin#599]

**Comment by foucdeg** [comment]
Oui c'est pas mal. Et puis ça pourrait mieux utiliser l'espace du leaderboard. Du coup à droite le leaderboard et à gauche un bloc avec ton propre classement (si connecté) et un champ de recherche.

**Comment by LeoAnesi** [comment]
@RobotScribe @foucdeg de ce que je vois sur la prod c'est done, je peux close ?

**Comment by foucdeg** [comment]
Yes
