### ISSUE TITLE
Pouvoir voter pour le premier mot

### ISSUE THREAD

**Issue by RobotScribe** [foucdeg/passe-un-dessin#600]

**Comment by foucdeg** [comment]
Why not, par contre ça va peut-être être relou niveau BDD si on doit stocker des votes à la fois sur les Pad et PadStep. A étudier.
Potentiellement faudra aussi revoir le calcul du nombre de votes.

**Comment by RobotScribe** [comment]
> Why not, par contre ça va peut-être être relou niveau BDD si on doit stocker des votes à la fois sur les Pad et PadStep. A étudier.
> Potentiellement faudra aussi revoir le calcul du nombre de votes.

Ouais j'avais pas pensé à ça pour la technique. Par contre c'est une feature assez demandée

**Comment by foucdeg** [comment]
oui en effet.

**Comment by foucdeg** [comment]
Autre approche : refacto du modèle pour que l'étape initale d'un pad soit une PadStep.
