### ISSUE TITLE
Les propositions de mots sont des mots déjà proposés dans le jeu

### ISSUE THREAD

**Issue by RobotScribe** [foucdeg/passe-un-dessin#601]
Cron qui tourne toutes les semaines et qui importe des données dans une table est requêtée par la route.
ça shoot un mail et Foucauld lance une commande qui dit OK.

- [x] seuil (5, 10 ?)
- [x] On prend les pad ou padstep
- [x] pouvoir filtrer par langue
- [x] pouvoir filtrer les mots pas cools
- [x] Pouvoir blacklister des mots
- [x] Droper articles, espaces, caractères spéciaux, remplacer les accents
- [x] Commande pour corriger l'ortographe
- [x] Cleaner suggestion.py
- [ ] Cron qui envoie des mails
- [x] mail compte mailgun on n'envoie que les nouveaux mots
- [x] Créer une commande pour corriger une phrase
- [x] Importer les mots de skribble

**Comment by foucdeg** [comment]
Alors à mon avis ça va être compliqué de filtrer :

- dès que ça dérape les gens commencent à mettre des trucs abscons du genre "le général de Gaulle mais avec un nez de clown sur l'auriculaire gauche" que tu veux pas avoir comme suggestions
- même en mot initial les gens mettent des inside jokes, parlent de leurs potes

**Comment by RobotScribe** [comment]
> Alors à mon avis ça va être compliqué de filtrer :
> 
> * dès que ça dérape les gens commencent à mettre des trucs abscons du genre "le général de Gaulle mais avec un nez de clown sur l'auriculaire gauche" que tu veux pas avoir comme suggestions. Avec la streameuse avec qui j'ai joué les deux derniers soirs, même les premiers mots c'était comme ça.
> * même en mot initial les gens mettent des inside jokes, parlent de leurs potes, tu veux pas ça non plus

On peut essayer de faire un truc smart qui compute les N propositions les plus utilisées dans des games différentes comme ça ça élimine les longues phrases qui sont souvent des private jokes. ça doit âs être trop dur à faire on peut fare un cron qui calcule ça toutes les semaines par exemple

**Comment by RobotScribe** [comment]
Le problème c'est de différrencier les langues par contre

**Comment by RobotScribe** [comment]
> Le problème c'est de différrencier les langues par contre

Ou alors on utilise ça https://pypi.org/project/langdetect/

**Comment by foucdeg** [comment]
Pas envie de me plonger dans des "trucs smart" / du NLP / de la data science perso, mais si quelqu'un veut explorer why not. 
Je vais juste être exigeant sur la qualité des suggestions qu'il sort, genre s'il me sort une seule fois "la grosse bite à Jérôme" c'est KO

**Comment by foucdeg** [comment]
c'est done ça
