### ISSUE TITLE
Je ne peux pas voir une game à laquelle je n'ai pas participé

### ISSUE THREAD

**Issue by RobotScribe** [foucdeg/passe-un-dessin#605]

**Comment by foucdeg** [comment]
Pourquoi pas ?

**Comment by RobotScribe** [comment]
une feature. je sais pas ça peut poser des questiions de privacy si tu veux faire des private jokes dans une partie mais tu veux pas forcément que d'autres personnes voient ce que tu as fait

**Comment by foucdeg** [comment]
C'est pas l'esprit. 
- En termes légaux tous les dessins / mots m'appartiennent, j'ai mis ça dans les conditions d'utilisation
- si je mets en place des ACL je ne peux plus mettre en valeur un dessin stylé comme je le fais sur la home actuellement, ni que les gens se partagent leurs games plutôt que de les screenshot, comme je leur propose dans le discord.
- enfin, si t'es dans le leaderboard, ça me paraît normal que les autres gens puissent aller voir pourquoi tu as eu plein de votes.

_A la limite_ un flag à la fin qui permet de dire que tu ne veux pas que ta partie apparaisse dans ton historique, mais ça me ferait mal que des gens l'utilisent.

**Comment by RobotScribe** [comment]
ok c'était un retour qu'on m'avait fait, je l'ai mis la pour partager mais si t'es contre no soucis
