### ISSUE TITLE
Retours potes de Quentin

### ISSUE THREAD

**Issue by foucdeg** [foucdeg/passe-un-dessin#68]
### Design

> Canvas sur les écrans pas larges

On a besoin d'une taille de canvas iso pour tout le monde sinon c'est injuste.

> Trop de noms ça casse le design des utilsateurs en haut de la page
> Sur petit écran et beaucoup de gens, quand on est admin, les boutons recouvrent les boutons des carnets
> Sur grande fenetre, le score touche

Issue #69  pour améliorer les glitchs visuels en cas de grand nombre de joueurs (michèle)

> Sur la Home PASSE-UN-DESSIN est en plusieurs lignes

Alors c'est une feature mais on est pas iso au design, peut-être que si on l'était ça serait plus clair ? Issue #70 -> done

### Feature

> Machine learning sur les dessins

Issue #72 

> Ne pas deviner son propre dessin

Issue #73, Quentin est dessus

> Sur Firefox filtre qui font que tu vois bien pour un daltonien

Chaud pour comprendre le besoin. La couleur est useless à part dans les dessins, donc les daltoniens ne ratent rien. Et comment faire dans les dessins ? Andon FrançoisF. Issue #74

> Voir les onglets sur lesquels tu as voté

Bonne idée, un petit compteur de likes dans l'onglet. Issue #75

> Voter pour les descriptions

bon ok c'est pas mal demandé, Issue #76 -> done

> Quand les dessins se re-dessine (que la première fois) mais c’est quand même stylé la première fois

A voir avec la nouvelle lib. Issue #77

> Au récap : Pouvoir aussi voir les autres dessins

Pas compris ?

### Améliorations rapide

> Erreur see console à enlever

Issue #78 pour améliorer l'UI d'erreur, mais par contre, c'est intéressant de savoir quand il y en a, surtout ETQDev. Faudrait Sentry sinon (#21).

> Explication peut pas rentrer tant que la partie est pas finie

y'a un truc indiqué dans le lobby "Une partie est en cours. Reste ici pour être dans la suivante !", ça suffit pas ?

> Dans la salle d’attente utiliser un nom générique ex (lapin rose) pour distinguer une partie

Done

> Mettre le temps restant dans le dessin (les secondes qui descendent)

Yes, le design le prévoit -> issue #79

> Pour les daltoniens mettre un hover sur les couleurs

A quel endroit ? Issue #74 -> done

> Sur la page d’accueil mettre une animation du jeu pour les gens qui ne connaissent pas

chaud je suis pas graphiste mais why not. #80

### Bugs

> Bug sur quand quelqu’un rentre ça vire quelqu’un

A reproduire. #81

> Ré-envoyer le dessin si le call fail

Pas sûr que ce soit une bonne strat sachant que les deux raisons que le call fait une 400 c'est "dessin déjà soumis" et "dessin vide". Par contre si pb réseau oui. A voir comment on distingue. Issue #82

### Typos

> Espace avant « ? «  en anglais 

Done

> Toujours les même qu’on assiste (faute)

Pas compris ? C'est marqué "Toujours les mêmes qu'on attend". Pas reproduit

### Idées random

> Partager ça à squezzie / Gotaga / Antoine Daniel / Julfou / Domingo/ laink et terracid (ils trollent vachement) (dans à propos)

Quelqu'un les connaît ? :)

**Comment by foucdeg** [comment]
Hello @dimtion @RobotScribe il reste un truc que j'ai pas compris dans vos retours (et pour me permettre de close cette issue parce que tout est transformé en sous-issues) : 

> Au récap : Pouvoir aussi voir les autres dessins

J'ai pas compris ce que vous vouliez dire ?

**Comment by RobotScribe** [comment]
> Hello @dimtion @RobotScribe il reste un truc que j'ai pas compris dans vos retours (et pour me permettre de close cette issue parce que tout est transformé en sous-issues) :
> 
> > Au récap : Pouvoir aussi voir les autres dessins
> 
> J'ai pas compris ce que vous vouliez dire ?

Si je me souviens bien c'était pour pouvoir voir aussi les dessins qui ne sont pas sur le podium.
Après l'idée est venue comme ça c'est pas forcément une bonne idée

**Comment by foucdeg** [comment]
@RobotScribe ben le recap sert à ça, après le besoin c'est peut-être de revenir au récap (auquel cas Back marche)

**Comment by foucdeg** [comment]
Du coup j'ai créé une issue pour ça, j'archive celle-ci.
