### ISSUE TITLE
Accessibilité pour les daltoniens

### ISSUE THREAD

**Issue by foucdeg** [foucdeg/passe-un-dessin#74]
> Sur Firefox filtre qui font que tu vois bien pour un daltonien

Chaud pour comprendre le besoin. La couleur est useless à part dans les dessins, donc les daltoniens ne ratent rien. Et comment faire dans les dessins ? Andon FrançoisF

> Pour les daltoniens mettre un hover sur les couleurs

A quel endroit ?

**Comment by dimtion** [comment]
Salut,

Dans notre groupe on avait un Daltonien qui galérait beaucoup dans certain cas. Typiquement si le mot d'avant c'était "avion bleu" il n'était pas capable de distinguer sur la palette le vert du bleu et donc de savoir quel pinceau prendre.

Le filtre dans firefox c'est simplement une feature dans le panneau d'accessibilité qui permet au dev de visualiser le site comme s'il avait une forme de daltonisme:
<img width="315" alt="Screenshot 2020-05-04 at 07 59 02" src="https://user-images.githubusercontent.com/1964358/80980394-721ccb80-8ddd-11ea-82cb-2164e36c9bd4.png">
Ça permet au moins de faire des petits tweaks.

Je crois que "le hover sur les couleurs" c'est au moment où l'on choisis la couleur sur pour le pinceau.

Cela étant dit, le daltonisme c'est 5% de la population, et votre jeu est principalement un jeu de couleurs donc ça me paraitrait normal de ne pas prioriser ce problème dans un premier temps. Par ailleurs, entre bon amis ça nous a fait aussi rire de voir les couleurs parfois choisies de manière approximatives :)
